version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: consultep
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - consultep_network

  mockoon:
    build:
      context: ./mockoon
    container_name: mockoon-mock
    ports:
      - "3000:3000" # Mapeia a porta do Mockoon para a máquina host
    volumes:
      - ./mockoon/api_mockada_cep.json:/mockoon/api_mockada_cep.json:ro
      - ./mockoon/mockoon_config.json:/mockoon/mockoon_config.json:ro
    restart: always

volumes:
  mysql_data:

networks:
  consultep_network:
    driver: bridge
