version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: consultep
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - consultep_network

  mockoon:
    build:
      context: ./mockoon
    container_name: mockoon-mock
    ports:
      - "3000:3000"
    volumes:
      - ./mockoon/api_mockada_cep.json:/mockoon/api_mockada_cep.json:ro
      - ./mockoon/mockoon_config.json:/mockoon/mockoon_config.json:ro
    restart: always
    networks:
      - consultep_network

  springboot-app:
    build:
      context: ..
      dockerfile: Dockerfile # Dockerfile na raiz do projeto
    container_name: springboot-app
    ports:
      - "8080:8080" # Porta da aplicação Spring Boot
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/consultep
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - consultep_network

volumes:
  mysql_data:

networks:
  consultep_network:
    driver: bridge
